import { demoMoments } from './data.js';
import { keys, labels, calculateFangyuanIndex, grade } from './scoring.js';

const STORE = 'novel-roast-v1';
const defaultState = () => ({ moments: demoMoments, activeId: demoMoments[0].id, stage: 'hook', scoreVisible: false, questionVisible: false, intense: false });
let state;
try { state = JSON.parse(localStorage.getItem(STORE) || 'null') || defaultState(); } catch { state = defaultState(); }
if (!Array.isArray(state.moments) || state.moments.length === 0) state = defaultState();
if (!state.moments.some(moment => moment.id === state.activeId)) state.activeId = state.moments[0].id;
const channel = 'BroadcastChannel' in window ? new BroadcastChannel('novel-roast-live') : null;
let liveSocket;
let connectionStatus = 'connecting';
let reconnectDelay = 1500;
let reconnectTimer;
let keepaliveTimer;
let fallbackPollTimer;
let adminAuthChecked = false;
let adminAuthorized = false;
const getWebSocketUrl = () => `${window.location.protocol === 'https:' ? 'wss:' : 'ws:'}//${window.location.host}`;
const getAdminToken = () => sessionStorage.getItem('novel-roast-admin-token') || '';
const refreshLiveState = async () => { try { const response = await fetch('/api/live-state', { cache: 'no-store' }); const { payload } = await response.json(); if (payload?.moments?.length) { state = payload; if (route() === 'live') render(); } } catch {} };
const startFallbackPolling = () => { if (!fallbackPollTimer && route() === 'live') { refreshLiveState(); fallbackPollTimer = window.setInterval(refreshLiveState, 3000); } };
const stopFallbackPolling = () => { clearInterval(fallbackPollTimer); fallbackPollTimer = undefined; };
window.setInterval(() => { if (route() === 'live') refreshLiveState(); if (route() === 'admin' && adminAuthorized) publishLiveState(); }, 2000);
const publishLiveState = () => { if (!adminAuthorized) return; fetch('/api/live-state', { method: 'POST', cache: 'no-store', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${getAdminToken()}` }, body: JSON.stringify({ payload: state }) }).catch(() => {}); };
const save = () => { localStorage.setItem(STORE, JSON.stringify(state)); channel?.postMessage(state); publishLiveState(); };
channel && (channel.onmessage = event => { state = event.data; render(); });
window.addEventListener('storage', event => { if(event.key === STORE) { state = JSON.parse(event.newValue); render(); } });
const active = () => state.moments.find(m => m.id === state.activeId) || state.moments[0];
const hydrateLiveControls = () => { const moment = active(); document.querySelectorAll('.pink-live-mark').forEach(mark => { const text = moment.book || '小说吐槽大会'; if (mark.textContent !== text) mark.textContent = text; }); const form = document.querySelector('.compact-form'); if (form && !form.querySelector('.score-axes')) { const section = document.createElement('section'); section.className = 'score-axes'; section.innerHTML = `<h2>方源指数六项指标</h2><div class="score-edit">${keys.map(key => `<label>${labels[key]}<input type="range" min="0" max="10" step="0.1" data-score="${key}" value="${moment.scores[key]}"><output>${moment.scores[key]}</output></label>`).join('')}</div><p>六项平均值自动计算为方源指数</p>`; form.append(section); } };
const syncPinkScoreBars = () => { const moment = active(); const aside = document.querySelector('.pink-live-bottom aside'); if (!aside) return; const signature = keys.map(key => moment.scores[key]).join(','); let bars = aside.querySelector('.dynamic-score-bars'); if (!bars) { bars = document.createElement('div'); bars.className = 'dynamic-score-bars'; aside.append(bars); } if (bars.dataset.signature === signature) return; bars.dataset.signature = signature; bars.innerHTML = keys.map(key => `<p><b>${labels[key]}</b><i><em style="width:${Math.min(100, Number(moment.scores[key]) * 10)}%"></em></i><strong>${Number(moment.scores[key]).toFixed(1)}</strong></p>`).join(''); };
const hydrateCinemaDisplay = () => { const moment = active(); const mark = document.querySelector('.show-mark'); if (!mark) return; const brand = moment.book || '小说吐槽大会', subtitle = moment.character || '方源指数 · 剧情吐槽直播', viewers = `✦ ${moment.viewerCount || '2.4 万'}人正在看`, verdictText = moment.verdict || '今日判词'; if (mark.textContent !== brand) mark.textContent = brand; const header = document.querySelector('.show-id'); if (header) { const [name, detail, count] = [header.querySelector('b'), header.querySelector('span'), header.querySelector('small')]; if (name.textContent !== brand) name.textContent = brand; if (detail.textContent !== subtitle) detail.textContent = subtitle; if (count.textContent !== viewers) count.textContent = viewers; } const verdict = document.querySelector('.cinema-header button'); if (verdict && verdict.dataset.verdict !== verdictText) { verdict.dataset.verdict = verdictText; verdict.textContent = verdictText; } };
const hydrateCinemaFields = () => { const moment = active(), form = document.querySelector('.compact-form'); if (!form || form.querySelector('.cinema-fields')) return; const section = document.createElement('section'); section.className = 'cinema-fields'; section.innerHTML = `<h2>图四文字补充</h2><div class="grid">${field('evidenceLabel','原文卡标题',moment.evidenceLabel || '原文证据')}${field('chapter','章节文字',moment.chapter || '第1章')}${field('sourceNote','来源文字',moment.sourceNote || moment.book || '')}${field('fyLabel','方源指数标题',moment.fyLabel || '方源指数')}${field('daaiLabel','大爱指数标题',moment.daaiLabel || '大爱指数')}</div></section>`; form.append(section); };
const syncCinemaCopy = () => { const moment = active(), evidence = document.querySelector('.evidence-paper'), fy = document.querySelector('.fy-score span'), daaiTitle = document.querySelector('.daai-stage span'); if (evidence) { const title = moment.evidenceLabel || '原文证据', source = `${moment.chapter || '第1章'} · ${moment.sourceNote || moment.book || ''}`; const [label, detail] = [evidence.querySelector('header b'), evidence.querySelector('header span')]; if (label.textContent !== title) label.textContent = title; if (detail.textContent !== source) detail.textContent = source; } if (fy && fy.textContent !== (moment.fyLabel || '方源指数')) fy.textContent = moment.fyLabel || '方源指数'; if (daaiTitle && daaiTitle.textContent !== `❤ ${moment.daaiLabel || '大爱指数'}`) daaiTitle.textContent = `❤ ${moment.daaiLabel || '大爱指数'}`; document.querySelectorAll('.score-line b').forEach((item, index) => { const key = keys[index], text = moment[`metricLabel_${key}`] || labels[key]; if (item.textContent !== text) item.textContent = text; }); };
const hydrateMetricLabels = () => { const moment = active(), form = document.querySelector('.compact-form'); if (!form || form.querySelector('.metric-labels')) return; const section = document.createElement('section'); section.className = 'metric-labels'; section.innerHTML = `<h2>六项指标名称</h2><div class="grid">${keys.map(key => field(`metricLabel_${key}`,`${labels[key]}显示名称`,moment[`metricLabel_${key}`] || labels[key])).join('')}</div></section>`; form.append(section); };
new MutationObserver(() => { hydrateLiveControls(); syncPinkScoreBars(); hydrateCinemaDisplay(); hydrateCinemaFields(); hydrateMetricLabels(); syncCinemaCopy(); }).observe(document.querySelector('#app'), { childList: true, subtree: true });
const escape = value => String(value || '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const daai = m => m.daaiIndex;
const route = () => location.pathname === '/live' ? 'live' : location.pathname === '/preview' ? 'preview' : location.pathname === '/admin' ? 'admin' : 'home';
function connectLiveSocket() { const currentRoute = route(); if (!['admin', 'live'].includes(currentRoute) || liveSocket?.readyState === WebSocket.OPEN || liveSocket?.readyState === WebSocket.CONNECTING) return; connectionStatus = 'connecting'; liveSocket = new WebSocket(getWebSocketUrl()); liveSocket.onopen = () => { connectionStatus = 'connected'; reconnectDelay = 1500; stopFallbackPolling(); liveSocket.send(JSON.stringify({ type: 'hello', role: currentRoute, adminKey: sessionStorage.getItem('novel-roast-admin-key') || '', adminToken: getAdminToken(), payload: currentRoute === 'admin' ? state : null })); clearInterval(keepaliveTimer); keepaliveTimer = window.setInterval(() => { if (liveSocket?.readyState === WebSocket.OPEN) liveSocket.send(JSON.stringify({ type: 'ping' })); }, 20000); render(); }; liveSocket.onmessage = event => { try { const message = JSON.parse(event.data); if (message.type === 'admin-auth' && currentRoute === 'admin') { adminAuthChecked = true; adminAuthorized = message.payload.ok; render(); } if (message.type === 'live-state' && message.payload?.moments?.length) { state = message.payload; if (currentRoute === 'live') render(); } } catch {} }; liveSocket.onclose = () => { connectionStatus = 'connecting'; liveSocket = undefined; clearInterval(keepaliveTimer); startFallbackPolling(); if (route() === 'live') render(); clearTimeout(reconnectTimer); reconnectTimer = window.setTimeout(connectLiveSocket, reconnectDelay); reconnectDelay = Math.min(reconnectDelay === 1500 ? 3000 : 5000, 5000); }; liveSocket.onerror = () => liveSocket.close(); }

function scoreCard(m, hidden=false) { return `<section class="score-card"><span>🔴 方源指数</span><strong class="score-number ${hidden?'concealed':''}">${hidden ? '???' : Number(m.fangyuanIndex).toFixed(1)}</strong><small>${hidden ? '等待公布' : grade(Number(m.fangyuanIndex))}</small></section><section class="score-card daai"><span>❤ 大爱指数</span><strong class="score-number ${hidden?'concealed':''}">${hidden ? '???' : daai(m)}</strong><small>反差娱乐评分</small></section>`; }
function liveCanvas(m, controls=false) { const rank = [...state.moments].sort((a,b)=>b.fangyuanIndex-a.fangyuanIndex).slice(0,3); const visible = stage => ['hook','evidence','roast','compare','question','score','ranking'].indexOf(state.stage) >= ['hook','evidence','roast','compare','question','score','ranking'].indexOf(stage); return `<main class="live-wrap ${state.intense?'intense':''}"><div class="live-canvas"><header><span class="brand">小说吐槽大会</span><span class="season">方源指数 · 直播中</span></header><section class="hook panel"><span>🔴 方源时刻 #${String(m.sequence).padStart(3,'0')}</span><h1>${escape(m.hook)}</h1><h2>${escape(m.title)}</h2></section>${visible('evidence')?`<section class="evidence panel"><b>关键文本 / 证据</b><p>${escape(m.originalText)}</p></section>`:''}${visible('roast')?`<section class="roast panel"><b>🎙 主播吐槽</b><p>${escape(m.roastText || '这一段，交给主播现场发挥。')}</p></section>`:''}${visible('compare')?`<section class="compare panel"><div><b>普通小说</b><p>${escape(m.conventionalTactic)}</p></div><i>VS</i><div><b>方源</b><p>${escape(m.fangyuanTactic)}</p></div></section>`:''}${visible('question')&&state.questionVisible?`<section class="question panel"><b>观众问题</b><p>${escape(m.audienceQuestion)}</p></section>`:''}${visible('score')?`<div class="scores">${scoreCard(m,!state.scoreVisible)}</div>`:''}${state.stage==='ranking'?`<section class="ranking panel"><b>🔴 本期方源指数 TOP 3</b>${rank.map((x,i)=>`<p>${i+1}. ${escape(x.title)} <strong>${x.fangyuanIndex}</strong></p>`).join('')}</section>`:''}</div>${controls?`<div class="live-controls"><button data-action="prev">← 上一个</button><button data-action="next">下一个 →</button><button data-action="stage">下一阶段</button><button data-action="question">${state.questionVisible?'隐藏':'显示'}问题</button><button data-action="score">公布评分</button><button data-action="intense">🔴 高潮模式</button></div>`:''}</main>`; }
function liveCinema(m) { if (!m) return `<main class="cinema-shell"><div class="cinema-canvas empty-live"><span>小说吐槽大会</span><h1>等待下一场<br>方源时刻</h1></div></main>`; const votes=[['A','该算',32],['B','不该算',18],['C','看收益',27],['D','太离谱了',23]]; return `<main class="cinema-shell"><article class="cinema-canvas"><div class="ink-wash wash-one"></div><div class="ink-wash wash-two"></div><header class="cinema-header"><div class="show-mark">小说<br>吐槽大会</div><div class="show-id"><b>小说吐槽大会</b><span>方源指数 · 剧情吐槽直播</span><small>🔥 2.4 万人正在看</small></div><button>＋ 关注</button></header><section class="cinema-hero"><span class="moment-label">方源时刻 #${String(m.sequence).padStart(3,'0')}</span><h1>${escape(m.hook)}</h1><p>${escape(m.subtitle || m.title || '普通主角不会这么想。')}</p></section><section class="cinema-main"><article class="evidence-paper"><header><b>📖 原文证据</b><span>${escape(m.chapter)} · ${escape(m.sourceNote || m.book)}</span></header><p>${escape(m.originalText || '暂无原文证据。')}</p><small>以上内容为用户自行录入的展示片段</small></article><aside class="score-stage"><div class="fy-score"><span>方源指数</span><strong>${m.fangyuanIndex.toFixed(1)}</strong><i>/ 10</i><small>${grade(m.fangyuanIndex)}</small></div><div class="score-lines">${keys.map(key=>`<div class="score-line ${key==='persistence'?'core-score':''}"><b>${key==='persistence'?'♛ ':''}${labels[key]}</b><i><em style="width:${m.scores[key]*10}%"></em></i><span>${Number(m.scores[key]).toFixed(1)}</span></div>`).join('')}</div><div class="daai-stage"><span>❤ 大爱指数</span><strong>${daai(m)}</strong><small>大爱仙尊认证</small></div></aside></section><section class="discussion"><header><b>💬 观众讨论</b><span>2.4 万人参与讨论</span></header><h2>${escape(m.audienceQuestion || '你觉得方源这波到底该不该算？')}</h2><div class="vote-list">${votes.map(([letter,label,pct])=>`<div><b>${letter}</b><span>${label}</span><i><em style="width:${pct}%"></em></i><strong>${pct}%</strong></div>`).join('')}</div></section></article></main>`; }
function admin() { const m=active(); return `<main class="compact-admin"><header><span>直播控制台</span><h1>${escape(m.book || '小说吐槽大会')}</h1><a href="/live" target="_blank">打开手机直播画面 ↗</a></header><form id="form" class="compact-form"><section><h2>顶部信息</h2><div class="grid">${field('book','直播名称',m.book || '小说吐槽大会')}${field('character','直播副标题',m.character || '方源指数 · 剧情吐槽直播')}${field('viewerCount','观看人数',m.viewerCount || '2.4 万')}${field('verdict','今日判词',m.verdict || '此局必胜')}</div></section><section><h2>本场内容</h2><div class="grid">${field('sequence','方源时刻编号',m.sequence)}${field('hook','主标题',m.hook)}${field('title','副标题',m.title)}</div>${area('originalText','原文证据',m.originalText)}</section><section><h2>指数展示</h2><div class="grid">${field('fangyuanIndex','方源指数（0–10）',m.fangyuanIndex)}${field('daaiIndex','大爱指数（可任意输入）',m.daaiIndex)}</div></section><p class="compact-save">自动保存并同步到手机直播端</p></form></main>`; }
const field=(key,label,value)=>`<label>${label}<input name="${key}" value="${escape(value)}"></label>`; const area=(key,label,value)=>`<label class="area">${label}<textarea name="${key}">${escape(value)}</textarea></label>`;
function home(){return `<div class="home"><span>🔴 小说吐槽大会</span><h1>方源指数<br>直播工作台</h1><p>把每一个“方源时刻”，变成可控、可播、可排行的节目单元。</p><a href="/admin">进入后台</a><a href="/live">进入直播</a></div>`;}
function adminGate(){return `<main class="home"><span>小说吐槽大会</span><h1>管理员控制码</h1><p>${adminAuthChecked ? '请输入部署时设置的管理员控制码。' : '正在连接直播服务；可先输入控制码。'}</p><form id="admin-key-form"><input id="admin-key-input" type="password" autocomplete="current-password" placeholder="管理员控制码"><button class="primary" type="submit">进入后台</button></form></main>`;}
function liveView(){ const moment = { ...active(), fangyuanIndex: Number(active().fangyuanIndex) || 0 }; return `<div class="live-stage">${liveCinema(moment)}</div><div class="connection-state ${connectionStatus}">● ${connectionStatus === 'connected' ? 'LIVE' : '正在连接'}</div><button class="fullscreen-live" id="fullscreen-live" aria-label="全屏直播画面">⛶</button>`; }
function render(){ const r=route(); document.querySelector('#app').innerHTML=r==='admin'?(adminAuthChecked&&adminAuthorized?admin():adminGate()):r==='live'?liveView():r==='preview'?`<div class="preview"><section>${admin()}</section><section>${liveCanvas(active(),true)}</section></div>`:home(); bind(); if(r==='admin'&&adminAuthorized){const strip=document.querySelector('.control-strip');const names={hook:'标题',evidence:'原文',roast:'吐槽',compare:'对比',question:'讨论',score:'评分'};strip?.insertAdjacentHTML('afterbegin',Object.entries(names).map(([stage,label])=>`<button class="${state.stage===stage?'active-stage':''}" data-stage="${stage}">${label}</button>`).join(''));} connectLiveSocket(); }
function bind(){ document.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{state.activeId=b.dataset.select;save();render()}); document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action)); const form=document.querySelector('#form'); form?.addEventListener('input', event=>{const m=active(),el=event.target;if(el.dataset.score){m.scores[el.dataset.score]=Number(el.value);m.fangyuanIndex=calculateFangyuanIndex(m.scores);el.nextElementSibling.value=el.value;const total=document.querySelector('#fy-index');if(total)total.textContent=`方源指数：${m.fangyuanIndex.toFixed(1)}`;}else if(el.name){m[el.name]=el.name==='tags'?el.value.split(',').map(x=>x.trim()).filter(Boolean):el.value;}m.updatedAt=new Date().toISOString();clearTimeout(window.autosave);window.autosave=setTimeout(save,500);}); document.querySelector('#daai-input')?.addEventListener('input', event=>{const value=Number(event.target.value);if(value>=0&&value<=10){const m=active();m.daaiIndex=value;m.daaiDisplayMode='normal';clearTimeout(window.autosave);window.autosave=setTimeout(save,250);}}); document.querySelectorAll('[data-daai]').forEach(b=>b.onclick=()=>{const m=active(),v=b.dataset.daai;m.daaiIndex=v==='over10'?10:v==='plus'?10:Number(v);m.daaiDisplayMode=v==='over10'?'over10':v==='plus'?'plus':'normal';save();render();}); const search=document.querySelector('#search');search?.addEventListener('input',()=>{const needle=search.value.trim().toLowerCase();document.querySelectorAll('.moment').forEach(item=>item.hidden=needle&&!item.textContent.toLowerCase().includes(needle));}); document.querySelector('#import')?.addEventListener('change', importData); }
function action(name){const m=active(),i=state.moments.indexOf(m);if(name==='live'){state.activeId=m.id;m.status='live';}if(name==='next'||name==='prev'){state.activeId=state.moments[(i+(name==='next'?1:-1)+state.moments.length)%state.moments.length].id;}if(name==='stage'){const list=['hook','evidence','roast','compare','question','score','ranking'];state.stage=list[(list.indexOf(state.stage)+1)%list.length];}if(name==='question')state.questionVisible=!state.questionVisible;if(name==='score')state.scoreVisible=true;if(name==='intense')state.intense=!state.intense;if(name==='new'){const n=structuredClone(m);n.id=crypto.randomUUID();n.sequence=Math.max(...state.moments.map(x=>x.sequence))+1;n.title='';n.hook='';n.chapter='';state.moments.push(n);state.activeId=n.id;}if(name==='duplicate'){const n=structuredClone(m);n.id=crypto.randomUUID();n.sequence=Math.max(...state.moments.map(x=>x.sequence))+1;n.title+='（副本）';state.moments.push(n);state.activeId=n.id;}if(name==='delete'&&confirm('确认删除这个 Moment？')){state.moments.splice(i,1);state.activeId=state.moments[0]?.id;}if(name==='export'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state.moments,null,2)],{type:'application/json'}));a.download=`moments-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();}save();render();}
function importData(e){const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const list=JSON.parse(reader.result);if(!Array.isArray(list))throw Error();state.moments=list;state.activeId=list[0]?.id;save();render();}catch{alert('JSON 格式无效');}};reader.readAsText(f);}
window.addEventListener('keydown',e=>{if(route()==='live'||route()==='preview'){if(e.code==='Space'){e.preventDefault();action('stage')}if(e.key.toLowerCase()==='n')action('next');if(e.key.toLowerCase()==='p')action('prev');if(e.key.toLowerCase()==='s')action('score');if(e.key.toLowerCase()==='h')action('intense');if(e.key.toLowerCase()==='q')action('question');}});document.addEventListener('click', event => { if (event.target.closest('#fullscreen-live')) document.documentElement.requestFullscreen?.(); if (event.target.closest('[data-stage]')) { state.stage = event.target.closest('[data-stage]').dataset.stage; save(); render(); } });document.addEventListener('submit', async event => { if (event.target.id === 'admin-key-form') { event.preventDefault(); const adminKey = document.querySelector('#admin-key-input').value; try { const response = await fetch('/api/admin-auth', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ adminKey }) }); const result = await response.json(); if (!response.ok || !result.ok) { alert('管理员控制码不正确。'); return; } sessionStorage.setItem('novel-roast-admin-key', adminKey); sessionStorage.setItem('novel-roast-admin-token', result.token); adminAuthChecked = true; adminAuthorized = true; liveSocket?.close(); render(); } catch { alert('无法连接后台认证服务，请稍后重试。'); } } });render();
